source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

xcodeproj 'LaunchKitSampleSwift.xcodeproj'
workspace 'LaunchKitDevSwift.xcworkspace'

target 'LaunchKitSampleSwift', :exclusive => true do
    pod "LaunchKit", :path => "../"
end

target 'LaunchKitSampleSwiftTests', :exclusive => true do
    pod "LaunchKit", :path => "../"
end

# See: http://stackoverflow.com/questions/21046282/debug-preprocessor-macro-not-defined-for-cocoapods-targets
# For 'Debug' configs, add LAUNCHKIT_(DEBUG|WARN|ERROR)=1 to the params
post_install do |installer_or_representation|
    installer = installer_or_representation.respond_to?(:installer) ? installer_or_representation.installer : installer_or_representation
    installer.pods_project.build_configurations.each do |config|
        if config.name.include?('Debug')
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']

            ['LAUNCHKIT_DEBUG=1', 'LAUNCHKIT_ERROR=1', 'LAUNCHKIT_WARN=1'].each do |param|
                if !config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include? param
                    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << param
                end
            end
        end
    end

end